From: Gitolite <devnull@kernel.org>
Subject: post-receive: pub/scm/git/git-htmldocs
Date: Mon, 11 Jul 2022 23:35:36 -0000
Message-Id: <165758253674.15826.11509995873292799910@gitolite.kernel.org>
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

---
service: git-receive-pack
repo: pub/scm/git/git-htmldocs
user: junio
changes:
  - ref: refs/heads/master
    old: ebdf143ff06ab8a67139c290755d6c6ecfe3126b
    new: 7bc735932830b9840daeff68819d626c3b0cd07b
    log: |
         7bc735932830b9840daeff68819d626c3b0cd07b Autogenerated HTML docs for v2.37.0-38-g55ece
         
