From: Gitolite <devnull@kernel.org>
Subject: post-receive: pub/scm/git/git-htmldocs
Date: Mon, 15 Nov 2021 16:55:29 -0000
Message-Id: <163699532905.864.15044899700125612198@gitolite.kernel.org>
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

---
service: git-receive-pack
repo: pub/scm/git/git-htmldocs
user: junio
changes:
  - ref: refs/heads/master
    old: e8fdbbb076c350daf2cd9921918f90610074189e
    new: f5008a039d585310d71e52b5d9f888dab4924eeb
    log: |
         f5008a039d585310d71e52b5d9f888dab4924eeb Autogenerated HTML docs for v2.34.0
         
