From: Gitolite <devnull@kernel.org>
Subject: post-receive: pub/scm/git/git-manpages
Date: Wed, 04 Mar 2026 23:03:38 -0000
Message-Id: <177266541883.3117321.15441509827918700989@gitolite.kernel.org>
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

---
service: git-receive-pack
repo: pub/scm/git/git-manpages
user: junio
changes:
  - ref: refs/heads/master
    old: a2bcdf8c60f1d6acd3ef7e5b6d2600f506ea705a
    new: 3c03d4c52d7915ff2a347fe5b156bc5bdc95326c
    log: |
         3c03d4c52d7915ff2a347fe5b156bc5bdc95326c Autogenerated manpages for v2.53.0-381-g628a6
         
